version: "3.8"
services:
  # tasks-api:
  #   image: syte/tasks-api
  #   container_name: syte-tasks-api
  #   ports:
  #   - 3022:3022
  #   environment: 
    # - MONGO_DB_NAME=syte 
    # - PORT=3022 
    # - MONGO_HOST=http://syte-mongodb:27017
    # - MONGO_USER=root 
    # - MONGO_PASSWORD=example
    # - GRPC_PORT=50051
    # - ENABLE_GRPC=true
  

  mongodb:
    image : mongo
    container_name: syte-mongodb
    volumes:
    - /tmp/mongodb/database:/data/db
    ports:
    - 27017:27017
    restart: unless-stopped